/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSeedRouteImport } from './routes/api.seed'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppFieldsRouteImport } from './routes/_app.fields'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as AppFieldsIdRouteImport } from './routes/_app.fields.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/api/public/[.well-known]/oauth-protected-resource'
import { Route as ApiPublicChar91DotmcpChar93ListToolsRouteImport } from './routes/api/public/[.mcp]/list-tools'
import { Route as ApiPublicChar91DotmcpChar93InvokeToolToolRouteImport } from './routes/api/public/[.mcp]/invoke-tool/$tool'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldsRoute = AppFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFieldsIdRoute = AppFieldsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFieldsRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute =
  ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/api/public/.well-known/oauth-protected-resource',
    path: '/api/public/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChar91DotmcpChar93ListToolsRoute =
  ApiPublicChar91DotmcpChar93ListToolsRouteImport.update({
    id: '/api/public/.mcp/list-tools',
    path: '/api/public/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChar91DotmcpChar93InvokeToolToolRoute =
  ApiPublicChar91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/api/public/.mcp/invoke-tool/$tool',
    path: '/api/public/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/fields': typeof AppFieldsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/api/seed': typeof ApiSeedRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/fields/$id': typeof AppFieldsIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/.mcp/list-tools': typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  '/api/public/.well-known/oauth-protected-resource': typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/public/.mcp/invoke-tool/$tool': typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/fields': typeof AppFieldsRouteWithChildren
  '/users': typeof AppUsersRoute
  '/api/seed': typeof ApiSeedRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/fields/$id': typeof AppFieldsIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/.mcp/list-tools': typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  '/api/public/.well-known/oauth-protected-resource': typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/public/.mcp/invoke-tool/$tool': typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fields': typeof AppFieldsRouteWithChildren
  '/_app/users': typeof AppUsersRoute
  '/api/seed': typeof ApiSeedRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_app/fields/$id': typeof AppFieldsIdRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/.mcp/list-tools': typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  '/api/public/.well-known/oauth-protected-resource': typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/public/.mcp/invoke-tool/$tool': typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/fields'
    | '/users'
    | '/api/seed'
    | '/.lovable/oauth/consent'
    | '/fields/$id'
    | '/api/public/mcp'
    | '/api/public/.mcp/list-tools'
    | '/api/public/.well-known/oauth-protected-resource'
    | '/api/public/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/fields'
    | '/users'
    | '/api/seed'
    | '/.lovable/oauth/consent'
    | '/fields/$id'
    | '/api/public/mcp'
    | '/api/public/.mcp/list-tools'
    | '/api/public/.well-known/oauth-protected-resource'
    | '/api/public/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/fields'
    | '/_app/users'
    | '/api/seed'
    | '/.lovable/oauth/consent'
    | '/_app/fields/$id'
    | '/api/public/mcp'
    | '/api/public/.mcp/list-tools'
    | '/api/public/.well-known/oauth-protected-resource'
    | '/api/public/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiSeedRoute: typeof ApiSeedRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicChar91DotmcpChar93ListToolsRoute: typeof ApiPublicChar91DotmcpChar93ListToolsRoute
  ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute: typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute
  ApiPublicChar91DotmcpChar93InvokeToolToolRoute: typeof ApiPublicChar91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fields': {
      id: '/_app/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof AppFieldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/fields/$id': {
      id: '/_app/fields/$id'
      path: '/$id'
      fullPath: '/fields/$id'
      preLoaderRoute: typeof AppFieldsIdRouteImport
      parentRoute: typeof AppFieldsRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/.well-known/oauth-protected-resource': {
      id: '/api/public/.well-known/oauth-protected-resource'
      path: '/api/public/.well-known/oauth-protected-resource'
      fullPath: '/api/public/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/.mcp/list-tools': {
      id: '/api/public/.mcp/list-tools'
      path: '/api/public/.mcp/list-tools'
      fullPath: '/api/public/.mcp/list-tools'
      preLoaderRoute: typeof ApiPublicChar91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/.mcp/invoke-tool/$tool': {
      id: '/api/public/.mcp/invoke-tool/$tool'
      path: '/api/public/.mcp/invoke-tool/$tool'
      fullPath: '/api/public/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof ApiPublicChar91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppFieldsRouteChildren {
  AppFieldsIdRoute: typeof AppFieldsIdRoute
}

const AppFieldsRouteChildren: AppFieldsRouteChildren = {
  AppFieldsIdRoute: AppFieldsIdRoute,
}

const AppFieldsRouteWithChildren = AppFieldsRoute._addFileChildren(
  AppFieldsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFieldsRoute: typeof AppFieldsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFieldsRoute: AppFieldsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiSeedRoute: ApiSeedRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicChar91DotmcpChar93ListToolsRoute:
    ApiPublicChar91DotmcpChar93ListToolsRoute,
  ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute:
    ApiPublicChar91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiPublicChar91DotmcpChar93InvokeToolToolRoute:
    ApiPublicChar91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
